<a href="https://colab.research.google.com/github/charlesdail/D205-PA/blob/main/LatestD206Num2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
#D206 Project
#by Charles Dail
#Fri Apr 22

#import necessary packages
import pandas as pd

#save csv in variable
medical_data = pd.read_csv('medical_raw_data.csv')

#detect missing values
medical_data.info()

#detect duplicates
medical_data[medical_data.duplicated()]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 53 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          10000 non-null  int64
 1   CaseOrder           10000 non-null  int64
 2   Customer_id         10000 non-null  object
 3   Interaction         10000 non-null  object
 4   UID                 10000 non-null  object
 5   City                10000 non-null  object
 6   State               10000 non-null  object
 7   County              10000 non-null  object
 8   Zip                 10000 non-null  int64
 9   Lat                 10000 non-null  float64
 10  Lng                 10000 non-null  float64
 11  Population          10000 non-null  int64
 12  Area                10000 non-null  object
 13  Timezone            10000 non-null  object
 14  Job                 10000 non-null  object
 15  Children            7412 non-null   float64
 16  Age                 7586 non-null   float64
 17  Education           10000 non-null  object
 18  Employment          10000 non-null  object
 19  Income              7536 non-null   float64
 20  Marital             10000 non-null  object
 21  Gender              10000 non-null  object
 22  ReAdmis             10000 non-null  object
 23  VitD_levels         10000 non-null  float64
 24  Doc_visits          10000 non-null  int64
 25  Full_meals_eaten    10000 non-null  int64
 26  VitD_supp           10000 non-null  int64
 27  Soft_drink          7533 non-null   object
 28  Initial_admin       10000 non-null  object
 29  HighBlood           10000 non-null  object
 30  Stroke              10000 non-null  object
 31  Complication_risk   10000 non-null  object
 32  Overweight          9018 non-null   float64
 33  Arthritis           10000 non-null  object
 34  Diabetes            10000 non-null  object
 35  Hyperlipidemia      10000 non-null  object
 36  BackPain            10000 non-null  object
 37  Anxiety             9016 non-null   float64
 38  Allergic_rhinitis   10000 non-null  object
 39  Reflux_esophagitis  10000 non-null  object
 40  Asthma              10000 non-null  object
 41  Services            10000 non-null  object
 42  Initial_days        8944 non-null   float64
 43  TotalCharge         10000 non-null  float64
 44  Additional_charges  10000 non-null  float64
 45  Item1               10000 non-null  int64
 46  Item2               10000 non-null  int64
 47  Item3               10000 non-null  int64
 48  Item4               10000 non-null  int64
 49  Item5               10000 non-null  int64
 50  Item6               10000 non-null  int64
 51  Item7               10000 non-null  int64
 52  Item8               10000 non-null  int64
dtypes: float64(11), int64(15), object(27)
memory usage: 4.0+ MB

Empty DataFrame
Columns: [Unnamed: 0, CaseOrder, Customer_id, Interaction, UID, City, State, County, Zip, Lat, Lng, Population, Area, Timezone, Job, Children, Age, Education, Employment, Income, Marital, Gender, ReAdmis, VitD_levels, Doc_visits, Full_meals_eaten, VitD_supp, Soft_drink, Initial_admin, HighBlood, Stroke, Complication_risk, Overweight, Arthritis, Diabetes, Hyperlipidemia, BackPain, Anxiety, Allergic_rhinitis, Reflux_esophagitis, Asthma, Services, Initial_days, TotalCharge, Additional_charges, Item1, Item2, Item3, Item4, Item5, Item6, Item7, Item8]
Index: []

[0 rows x 53 columns]